### ISSUE TITLE
Doesn't work with CloundLinux and CageFS

### ISSUE THREAD

**Issue by eracadmin** [thecpaneladmin/EA-PhalconPHP#6]
Hi there,

I spent quite a bit of time troubleshooting this with the cPanel guys who are very experienced. 

There seems to be a bug when trying to get it to work with CloudLinux and CageFS, it doesn;t even show in the PHP modules before building it. 

Please send me an email to maoz@techtone.ca so we can further discuss the solution for this issue. Thanks!

**Comment by vanessavasile** [comment]
In troubleshooting, was unable to reproduce the issue other than seeing that the module download was being killed halfway through, which resulted in a package that couldn't be extracted or compiled. Informed the original reporter about this and did not hear back. The solution:

" Since root SSH logins are disabled on this server, it's possible the problem is that EA is still running in an LVE and being limited on resources. Therefore, you may want to add your admin users to the 'wheel' group."
